import { createFloorScenario } from "@/harness/floor-scenario";
import { replayRoute, type RoutePlan, type RouteReplay } from "@/harness/route-replay";

export const PROVISIONAL_ROUTE: RoutePlan = {
  id: "provisional-main-route",
  label: "Provisional main route",
  commands: [
    "forward",
    "interact",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "interact",
    "forward",
    "interact",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "interact",
    "forward",
    "interact",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "interact",
    "forward",
    "forward",
    "forward",
    "turnRight",
    "forward",
    "forward",
    "turnLeft",
    "interact",
    "forward",
    "forward",
    "interact",
    "forward",
    "forward",
    "interact",
    "forward",
    "turnRight",
    "forward",
    "forward",
    "turnRight",
    "forward",
    "interact",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "turnRight",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
    "forward",
  ],
  checkpoints: [
    { id: "start", label: "B1 entry", commandIndex: 0 },
    { id: "b1-red-key", label: "B1 red key", commandIndex: 1, entityId: "b1-red-key" },
    { id: "b1-red-door", label: "B1 red route door", commandIndex: 2, entityId: "b1-red-door" },
    { id: "b1-down", label: "B2 entry", commandIndex: 8, entityId: "b1-down" },
    { id: "b2-blue-key", label: "B2 blue key", commandIndex: 9, entityId: "b2-blue-key" },
    { id: "b2-blue-door", label: "B2 blue attack door", commandIndex: 10, entityId: "b2-blue-door" },
    { id: "b2-down", label: "B3 entry", commandIndex: 19, entityId: "b2-down" },
    { id: "b3-yellow-key", label: "B3 yellow key", commandIndex: 20, entityId: "b3-yellow-key" },
    { id: "b3-yellow-door", label: "B3 yellow defense door", commandIndex: 21, entityId: "b3-yellow-door" },
    { id: "b3-blue-key", label: "B3 second blue key", commandIndex: 24, entityId: "b3-blue-key" },
    { id: "b3-down", label: "B4 entry", commandIndex: 30, entityId: "b3-down" },
    { id: "b4-red-key", label: "B4 red key", commandIndex: 31, entityId: "b4-red-key" },
    { id: "b4-yellow-key", label: "B4 yellow key", commandIndex: 32, entityId: "b4-yellow-key" },
    { id: "b4-blue-door", label: "B4 large blue door", commandIndex: 38, entityId: "b4-blue-door" },
    { id: "b4-red-door", label: "B4 red route door", commandIndex: 41, entityId: "b4-red-door" },
    { id: "b4-yellow-door", label: "B4 large yellow door", commandIndex: 44, entityId: "b4-yellow-door" },
    { id: "b4-down", label: "B5 entry", commandIndex: 51, entityId: "b4-down" },
    { id: "victory", label: "Princess defeated", commandIndex: 71, entityId: "b5-princess" },
  ],
};

/** Replays the provisional main route from a new canonical floor scenario. */
export function replayProvisionalRoute(): RouteReplay {
  const scenario = createFloorScenario();
  return replayRoute(scenario.session, PROVISIONAL_ROUTE);
}
